{
	"schema_version": "1.6.0",
	"id": "DSA-4476-1",
	"modified": "2023-10-16T00:17:44.025951Z",
	"published": "2019-07-05T00:00:00Z",
	"related": [
		"CVE-2019-12308",
		"CVE-2019-12781",
		"CVE-2019-6975"
	],
	"summary": "python-django - security update",
	"details": "\nThree security issues were found in Django, a Python web development\nframework, which could result in denial of service, incomplete\nsanitisation of clickable links or missing redirects of HTTP requests\nto HTTPS.\n\n\nFor the stable distribution (stretch), these problems have been fixed in\nversion 1:1.10.7-2+deb9u5.\n\n\nWe recommend that you upgrade your python-django packages.\n\n\nFor the detailed security status of python-django please refer to\nits security tracker page at:\n[\\\nhttps://security-tracker.debian.org/tracker/python-django](https://security-tracker.debian.org/tracker/python-django)\n\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:9",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.10.7-2+deb9u5"
						}
					]
				}
			],
			"versions": [
				"1:1.10.7-2",
				"1:1.10.7-2+deb9u1",
				"1:1.10.7-2+deb9u2",
				"1:1.10.7-2+deb9u3",
				"1:1.10.7-2+deb9u4"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-4476-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2019/dsa-4476"
		}
	]
}
