{
	"schema_version": "1.6.0",
	"id": "CVE-2024-3219",
	"modified": "2024-07-30T22:45:15.671692Z",
	"published": "2024-07-29T22:15:04Z",
	"aliases": [
		"PSF-2024-7"
	],
	"details": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "python3.11",
				"purl": "pkg:deb/debian/python3.11?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.11.2-6",
				"3.11.2-6+deb12u1",
				"3.11.2-6+deb12u2",
				"3.11.3-1",
				"3.11.3-2",
				"3.11.4-1",
				"3.11.5-1",
				"3.11.5-2",
				"3.11.5-3",
				"3.11.6-1",
				"3.11.6-2",
				"3.11.6-3",
				"3.11.6-3~hurd.2",
				"3.11.7-1",
				"3.11.7-2",
				"3.11.8-1",
				"3.11.8-1.1~exp1",
				"3.11.8-1.1~exp2",
				"3.11.8-2",
				"3.11.8-3",
				"3.11.8-3+hurd.1",
				"3.11.9-1"
			],
			"ecosystem_specific": {
				"urgency": "unimportant"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-3219.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python3.12",
				"purl": "pkg:deb/debian/python3.12?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.12.0-1",
				"3.12.0-2",
				"3.12.0-3",
				"3.12.0-4",
				"3.12.0-5",
				"3.12.0-6",
				"3.12.0-7",
				"3.12.0~a5-1",
				"3.12.0~a7-1",
				"3.12.0~b1-1",
				"3.12.0~b2-1",
				"3.12.0~b2-2",
				"3.12.0~b2-3",
				"3.12.0~b3-1",
				"3.12.0~b4-1",
				"3.12.0~rc1-1",
				"3.12.0~rc1-2",
				"3.12.0~rc2-1",
				"3.12.1-1",
				"3.12.1-2",
				"3.12.2-1",
				"3.12.2-1.1~exp1",
				"3.12.2-1.1~exp2",
				"3.12.2-2",
				"3.12.2-3",
				"3.12.2-4",
				"3.12.2-4+hurd.1",
				"3.12.2-5",
				"3.12.3-1",
				"3.12.4-1",
				"3.12.4-1+hurd.1",
				"3.12.4-1+hurd.2",
				"3.12.4-2",
				"3.12.4-3"
			],
			"ecosystem_specific": {
				"urgency": "unimportant"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-3219.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python3.13",
				"purl": "pkg:deb/debian/python3.13?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.13.0~a6-1",
				"3.13.0~b1-1",
				"3.13.0~b1-2",
				"3.13.0~b2-1",
				"3.13.0~b3-1",
				"3.13.0~b3-2",
				"3.13.0~b3-3",
				"3.13.0~b3-3+hurd.1",
				"3.13.0~b3-3+hurd.2",
				"3.13.0~b3-4",
				"3.13.0~b3-5",
				"3.13.0~b3-6",
				"3.13.0~b4-1"
			],
			"ecosystem_specific": {
				"urgency": "unimportant"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-3219.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python3.9",
				"purl": "pkg:deb/debian/python3.9?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.9.10-1",
				"3.9.10-2",
				"3.9.11-1",
				"3.9.12-1",
				"3.9.13-1",
				"3.9.2-1",
				"3.9.3-1",
				"3.9.3-2",
				"3.9.4-1",
				"3.9.5-1",
				"3.9.5-2",
				"3.9.5-3",
				"3.9.6-1",
				"3.9.7-1",
				"3.9.7-2",
				"3.9.7-4",
				"3.9.8-1",
				"3.9.8-2",
				"3.9.9-1",
				"3.9.9-2",
				"3.9.9-3",
				"3.9.9-4"
			],
			"ecosystem_specific": {
				"urgency": "unimportant"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-3219.json"
			}
		}
	],
	"references": [
		{
			"type": "FIX",
			"url": "https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20"
		},
		{
			"type": "FIX",
			"url": "https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2"
		},
		{
			"type": "FIX",
			"url": "https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c"
		},
		{
			"type": "FIX",
			"url": "https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929"
		},
		{
			"type": "FIX",
			"url": "https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/python/cpython/issues/122133"
		},
		{
			"type": "WEB",
			"url": "http://www.openwall.com/lists/oss-security/2024/07/29/3"
		},
		{
			"type": "WEB",
			"url": "https://github.com/python/cpython/pull/122134"
		},
		{
			"type": "WEB",
			"url": "https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2024-3219"
		}
	]
}
