{
	"schema_version": "1.6.0",
	"id": "DLA-2456-1",
	"modified": "2024-01-09T20:32:37.476118Z",
	"published": "2020-11-18T00:00:00Z",
	"related": [
		"CVE-2019-20907",
		"CVE-2020-26116"
	],
	"summary": "python3.5 - security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:9",
				"name": "python3.5",
				"purl": "pkg:deb/debian/python3.5?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.5.3-1+deb9u3"
						}
					]
				}
			],
			"versions": [
				"3.5.3-1",
				"3.5.3-1+deb9u1",
				"3.5.3-1+deb9u2"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-2456-1.json"
			}
		}
	]
}
