{
	"schema_version": "1.6.0",
	"id": "CVE-2019-14859",
	"modified": "2024-09-18T03:02:33.258495Z",
	"published": "2020-01-02T15:15:11Z",
	"aliases": [
		"GHSA-8qxj-f9rh-9fg2",
		"PYSEC-2020-163"
	],
	"related": [
		"DLA-1978-1",
		"DSA-4588-1",
		"SUSE-SU-2019:2891-1",
		"SUSE-SU-2019:2891-2",
		"SUSE-SU-2019:3024-1",
		"USN-4196-1",
		"openSUSE-SU-2019:2472-1",
		"openSUSE-SU-2019:2474-1",
		"openSUSE-SU-2024:11229-1",
		"openSUSE-SU-2024:13862-1"
	],
	"details": "A flaw was found in all python-ecdsa versions before 0.13.3, where it did not correctly verify whether signatures used DER encoding. Without this verification, a malformed signature could be accepted, making the signature malleable. Without proper verification, an attacker could use a malleable signature to create false transactions.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-ecdsa",
				"purl": "pkg:deb/debian/python-ecdsa?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.13.3-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-14859.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "python-ecdsa",
				"purl": "pkg:deb/debian/python-ecdsa?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.13.3-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-14859.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python-ecdsa",
				"purl": "pkg:deb/debian/python-ecdsa?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.13.3-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-14859.json"
			}
		},
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/warner/python-ecdsa",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "7add2213c992f51267eed8288b560f3f4108a28d"
						}
					]
				}
			],
			"versions": [
				"python-ecdsa-0.10",
				"python-ecdsa-0.11",
				"python-ecdsa-0.12",
				"python-ecdsa-0.13",
				"python-ecdsa-0.13.1",
				"python-ecdsa-0.13.2",
				"python-ecdsa-0.5",
				"python-ecdsa-0.6",
				"python-ecdsa-0.7",
				"python-ecdsa-0.8",
				"python-ecdsa-0.9"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-14859.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14859"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/warner/python-ecdsa/issues/114"
		},
		{
			"type": "PACKAGE",
			"url": "https://pypi.org/project/ecdsa/0.13.3/"
		},
		{
			"type": "WEB",
			"url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2019-14859"
		}
	]
}
