{
	"schema_version": "1.6.0",
	"id": "CVE-2020-13596",
	"modified": "2024-09-18T03:07:29.401077Z",
	"published": "2020-06-03T14:15:12Z",
	"aliases": [
		"BIT-django-2020-13596",
		"GHSA-2m34-jcjv-45xf",
		"PYSEC-2020-32"
	],
	"related": [
		"DLA-2233-1",
		"DSA-4705-1",
		"USN-4381-1",
		"USN-4381-2"
	],
	"details": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2:2.2.13-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-13596.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2:2.2.13-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-13596.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2:2.2.13-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-13596.json"
			}
		},
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/django/django",
					"events": [
						{
							"introduced": "635d53a86a36cde7866b9caefeb64d809e6bfcd9"
						},
						{
							"fixed": "8093aaa8ff9dd7386a069c6eb49fcc1c5980c033"
						}
					]
				}
			],
			"versions": [
				"2.2",
				"2.2.1",
				"2.2.10",
				"2.2.11",
				"2.2.12",
				"2.2.2",
				"2.2.3",
				"2.2.4",
				"2.2.5",
				"2.2.6",
				"2.2.7",
				"2.2.8",
				"2.2.9"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-13596.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://docs.djangoproject.com/en/3.0/releases/security/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.netapp.com/advisory/ntap-20200611-0002/"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2020/dsa-4705"
		},
		{
			"type": "ARTICLE",
			"url": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
		},
		{
			"type": "WEB",
			"url": "https://www.oracle.com/security-alerts/cpujan2021.html"
		},
		{
			"type": "WEB",
			"url": "https://groups.google.com/forum/#%21msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"
		},
		{
			"type": "WEB",
			"url": "https://usn.ubuntu.com/4381-1/"
		},
		{
			"type": "WEB",
			"url": "https://usn.ubuntu.com/4381-2/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2020-13596"
		}
	]
}
